version: "3.8"
services:
  bootcamp-project:
    container_name: bootcamp_project
    image: ${DOCKER_HUB_CREDS_USR}/bootcamp_project:latest
    build: .
    ports:
    - published: 80
      target: 5000
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@bootcamp_database:3306/project
      CREATE_SCHEMA: 
    depends_on:
    - database
  database:
    container_name: bootcamp_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
    ports:
    - published:
      target: 3360
    volumes:
    - type: volume
      source: bootcamp_database_volume
      target: /var/lib/mysql
volumes:
  bootcamp_database_volume:

# 