pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
    }
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                sh "bash jenkins/build.sh"
            }
        }
        stage('Push') {
            steps {
                sh "bash jenkins/push.sh"
            }
        }
        stage('Deploy') {
            steps {
                checkout scm
                /*
                * In order to communicate with the MySQL server, this Pipeline explicitly
                * maps the port (`3306`) to a known port on the host machine.
                */
                docker.image('mysql:5.7').withRun('-e "MYSQL_ROOT_PASSWORD=my-secret-pw" -p 3306:3306')
                sh 'while ! mysqladmin ping -h0.0.0.0 --silent; do sleep 1; done'
                sh "bash jenkins/deploy.sh"
            }
        } 
    }
}
